# Final

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!gdown --id 1dkIQbawpE7BKnxGh_OTKI1qVHWCuhCXh # mtp_data.csv
!gdown --id 1g6l_m0Qdxqg_LLed5W73EfB8ZZpwxAzR # run svr
!gdown --id 1e_OMi-qlD1LDrEPwJY7cXYH8uuIUzhB5 # run lstm
!gdown --id 1T8NpfQ_cSq5yXGBtrblLSquszd4dH_tg # run lr
!gdown --id 1OTlVP9h2cM6j89C3MSjzaYhehwPUphZq # lr asset selection
!gdown --id 1b1IxAxjZo29GeMbz1vbcaSuVnHCnB7LL # svr asset selection
!gdown --id 1-g7ypg87-io1Pp2Cci9Z2q8nGluA8oVp # lstm asset selection

In [ ]:
pd.read_csv('/content/mtp_data.csv', index_col=0).head()

,^NSEI,ONGC.NS,UPL.NS,ITC.NS,SUNPHARMA.NS,IOC.NS,JSWSTEEL.NS,SBIN.NS,SHREECEM.NS,HINDUNILVR.NS,...,KOTAKBANK.NS,BAJAJFINSV.NS,POWERGRID.NS,ASIANPAINT.NS,EICHERMOT.NS,TATAMOTORS.NS,DRREDDY.NS,HDFCBANK.NS,HDFC.NS,MARUTI.NS
0,10283.599609,142.570755,461.820221,219.472366,497.929108,137.465652,243.074020,334.412537,17980.212891,1207.996460,...,1021.619751,5122.470215,124.082924,1140.235840,2765.153076,421.799988,2228.211426,895.502197,1609.008423,7966.571289
1,10298.750000,144.497406,464.817383,220.493179,497.977264,136.700287,242.481430,329.953705,17216.855469,1204.546875,...,1038.942871,5166.208008,124.201874,1135.416992,2759.052246,423.000000,2182.017822,901.682983,1593.630493,8040.337402
2,10326.900391,145.219864,481.142456,217.600906,518.102356,137.813507,245.125443,327.625183,16725.525391,1207.240234,...,1028.259399,5198.812012,122.893265,1129.527710,2739.318359,424.250000,2296.853027,905.656372,1598.630859,8039.525879
3,10342.299805,145.541016,476.423492,219.599976,515.406250,137.761353,244.851959,332.232635,16819.513672,1200.719116,...,1024.664917,5169.003906,123.160934,1143.156372,2717.494873,428.600006,2264.714844,910.071228,1620.942749,8123.835449
4,10348.750000,145.862076,477.762665,219.599976,524.553955,137.326477,243.301971,331.885864,16929.433594,1197.930908,...,1020.521423,5126.314941,124.350624,1128.845825,2757.274170,426.250000,2212.525879,903.988525,1608.159302,8076.360840

In [ ]:
# %pycat run_lstm_train.sh

In [ ]:
# %%writefile run_lstm_train.sh

Overwriting run_lstm_train.sh

In [ ]:
!bash run_lr_train.sh

(954, 51)
(954, 51)
(954, 51)
(954, 51)
(954, 51)

In [ ]:
!bash run_svr_train.sh

(954, 51)
(954, 51)
(954, 51)
(954, 51)
(954, 51)

In [ ]:
!bash run_lstm_train.sh

Model Updated
Epoch: 0, train loss: 0.26649, val loss: 0.11721
Model Updated
Epoch: 100, train loss: 0.00490, val loss: 0.01681
Model Updated
Epoch: 200, train loss: 0.00234, val loss: 0.01453
Model Updated
Epoch: 300, train loss: 0.00165, val loss: 0.01187
Model Updated
Epoch: 400, train loss: 0.00131, val loss: 0.01082
Model Updated
Epoch: 500, train loss: 0.00121, val loss: 0.01040
Model Updated
Epoch: 600, train loss: 0.00095, val loss: 0.00924
Model Updated
Epoch: 700, train loss: 0.00090, val loss: 0.00850
Model Updated
Epoch: 800, train loss: 0.00091, val loss: 0.00757
Model Updated
Epoch: 900, train loss: 0.00074, val loss: 0.00713
Model Updated
Epoch: 1000, train loss: 0.00065, val loss: 0.00701
Model Updated
Epoch: 1100, train loss: 0.00060, val loss: 0.00666
Model Updated
Epoch: 1200, train loss: 0.00058, val loss: 0.00663
Epoch: 1300, train loss: 0.00057, val loss: 0.00663
Model Updated
Epoch: 1400, train loss: 0.00051, val loss: 0.00632
Model Updated
Epoch: 1500, train loss: 0.00060, val loss: 0.00599
Epoch: 1600, train loss: 0.00046, val loss: 0.00604
Epoch: 1700, train loss: 0.00048, val loss: 0.00611
Model Updated
Epoch: 1800, train loss: 0.00044, val loss: 0.00568
Epoch: 1900, train loss: 0.00052, val loss: 0.00573
Model Updated
Epoch: 2000, train loss: 0.00041, val loss: 0.00551
Epoch: 2100, train loss: 0.00044, val loss: 0.00567
Model Updated
Epoch: 2200, train loss: 0.00040, val loss: 0.00537
Model Updated
Epoch: 2300, train loss: 0.00036, val loss: 0.00511
Epoch: 2400, train loss: 0.00038, val loss: 0.00544
Epoch: 2500, train loss: 0.00040, val loss: 0.00545
Model Updated
Epoch: 2600, train loss: 0.00033, val loss: 0.00501
Model Updated
Epoch: 2700, train loss: 0.00031, val loss: 0.00495
Epoch: 2800, train loss: 0.00042, val loss: 0.00501
Epoch: 2900, train loss: 0.00043, val loss: 0.00496
(20, 51)
(954, 51)
Model Updated
Epoch: 0, train loss: 0.26783, val loss: 0.10861
Model Updated
Epoch: 100, train loss: 0.00487, val loss: 0.01530
Model Updated
Epoch: 200, train loss: 0.00243, val loss: 0.00970
Model Updated
Epoch: 300, train loss: 0.00174, val loss: 0.00723
Model Updated
Epoch: 400, train loss: 0.00143, val loss: 0.00630
Model Updated
Epoch: 500, train loss: 0.00124, val loss: 0.00585
Model Updated
Epoch: 600, train loss: 0.00108, val loss: 0.00540
Model Updated
Epoch: 700, train loss: 0.00095, val loss: 0.00517
Model Updated
Epoch: 800, train loss: 0.00084, val loss: 0.00513
Epoch: 900, train loss: 0.00077, val loss: 0.00513
Epoch: 1000, train loss: 0.00086, val loss: 0.00543
Model Updated
Epoch: 1100, train loss: 0.00068, val loss: 0.00498
Model Updated
Epoch: 1200, train loss: 0.00062, val loss: 0.00492
Model Updated
Epoch: 1300, train loss: 0.00059, val loss: 0.00483
Model Updated
Epoch: 1400, train loss: 0.00059, val loss: 0.00481
Epoch: 1500, train loss: 0.00055, val loss: 0.00486
Epoch: 1600, train loss: 0.00064, val loss: 0.00499
Model Updated
Epoch: 1700, train loss: 0.00052, val loss: 0.00471
Model Updated
Epoch: 1800, train loss: 0.00047, val loss: 0.00459
Epoch: 1900, train loss: 0.00047, val loss: 0.00466
Epoch: 2000, train loss: 0.00046, val loss: 0.00466
Model Updated
Epoch: 2100, train loss: 0.00043, val loss: 0.00459
Model Updated
Epoch: 2200, train loss: 0.00042, val loss: 0.00455
Epoch: 2300, train loss: 0.00042, val loss: 0.00460
Epoch: 2400, train loss: 0.00041, val loss: 0.00455
Epoch: 2500, train loss: 0.00055, val loss: 0.00506
Model Updated
Epoch: 2600, train loss: 0.00037, val loss: 0.00454
Epoch: 2700, train loss: 0.00039, val loss: 0.00476
Epoch: 2800, train loss: 0.00036, val loss: 0.00457
Epoch: 2900, train loss: 0.00039, val loss: 0.00471
(39, 51)
(954, 51)
Model Updated
Epoch: 0, train loss: 0.26852, val loss: 0.12504
Model Updated
Epoch: 100, train loss: 0.00472, val loss: 0.02680
Model Updated
Epoch: 200, train loss: 0.00255, val loss: 0.02170
Epoch: 300, train loss: 0.00188, val loss: 0.02212
Model Updated
Epoch: 400, train loss: 0.00171, val loss: 0.02150
Model Updated
Epoch: 500, train loss: 0.00130, val loss: 0.01991
Model Updated
Epoch: 600, train loss: 0.00112, val loss: 0.01768
Model Updated
Epoch: 700, train loss: 0.00099, val loss: 0.01658
Model Updated
Epoch: 800, train loss: 0.00088, val loss: 0.01651
Epoch: 900, train loss: 0.00086, val loss: 0.01656
Model Updated
Epoch: 1000, train loss: 0.00073, val loss: 0.01619
Model Updated
Epoch: 1100, train loss: 0.00073, val loss: 0.01597
Model Updated
Epoch: 1200, train loss: 0.00066, val loss: 0.01509
Epoch: 1300, train loss: 0.00065, val loss: 0.01534
Epoch: 1400, train loss: 0.00087, val loss: 0.01517
Model Updated
Epoch: 1500, train loss: 0.00056, val loss: 0.01435
Epoch: 1600, train loss: 0.00077, val loss: 0.01479
Model Updated
Epoch: 1700, train loss: 0.00055, val loss: 0.01422
Model Updated
Epoch: 1800, train loss: 0.00056, val loss: 0.01350
Epoch: 1900, train loss: 0.00048, val loss: 0.01356
Epoch: 2000, train loss: 0.00046, val loss: 0.01375
Epoch: 2100, train loss: 0.00057, val loss: 0.01455
Epoch: 2200, train loss: 0.00043, val loss: 0.01351
Epoch: 2300, train loss: 0.00042, val loss: 0.01381
Epoch: 2400, train loss: 0.00041, val loss: 0.01377
Epoch: 2500, train loss: 0.00040, val loss: 0.01367
Epoch: 2600, train loss: 0.00042, val loss: 0.01363
Epoch: 2700, train loss: 0.00039, val loss: 0.01397
Epoch: 2800, train loss: 0.00036, val loss: 0.01438
Epoch: 2900, train loss: 0.00036, val loss: 0.01410
(58, 51)
(954, 51)
Model Updated
Epoch: 0, train loss: 0.27097, val loss: 0.14889
Model Updated
Epoch: 100, train loss: 0.00522, val loss: 0.04453
Model Updated
Epoch: 200, train loss: 0.00309, val loss: 0.03780
Model Updated
Epoch: 300, train loss: 0.00201, val loss: 0.03329
Epoch: 400, train loss: 0.00153, val loss: 0.03362
Model Updated
Epoch: 500, train loss: 0.00125, val loss: 0.03215
Model Updated
Epoch: 600, train loss: 0.00109, val loss: 0.03103
Model Updated
Epoch: 700, train loss: 0.00097, val loss: 0.03046
Model Updated
Epoch: 800, train loss: 0.00088, val loss: 0.03025
Model Updated
Epoch: 900, train loss: 0.00085, val loss: 0.02977
Model Updated
Epoch: 1000, train loss: 0.00077, val loss: 0.02889
Model Updated
Epoch: 1100, train loss: 0.00076, val loss: 0.02839
Model Updated
Epoch: 1200, train loss: 0.00070, val loss: 0.02750
Model Updated
Epoch: 1300, train loss: 0.00067, val loss: 0.02710
Epoch: 1400, train loss: 0.00075, val loss: 0.02715
Model Updated
Epoch: 1500, train loss: 0.00061, val loss: 0.02583
Epoch: 1600, train loss: 0.00063, val loss: 0.02592
Model Updated
Epoch: 1700, train loss: 0.00058, val loss: 0.02537
Epoch: 1800, train loss: 0.00056, val loss: 0.02556
Model Updated
Epoch: 1900, train loss: 0.00051, val loss: 0.02476
Model Updated
Epoch: 2000, train loss: 0.00053, val loss: 0.02458
Epoch: 2100, train loss: 0.00047, val loss: 0.02460
Epoch: 2200, train loss: 0.00046, val loss: 0.02489
Epoch: 2300, train loss: 0.00045, val loss: 0.02474
Epoch: 2400, train loss: 0.00043, val loss: 0.02468
Model Updated
Epoch: 2500, train loss: 0.00042, val loss: 0.02452
Model Updated
Epoch: 2600, train loss: 0.00045, val loss: 0.02432
Epoch: 2700, train loss: 0.00039, val loss: 0.02456
Epoch: 2800, train loss: 0.00038, val loss: 0.02449
Epoch: 2900, train loss: 0.00038, val loss: 0.02434
(77, 51)
(954, 51)
Model Updated
Epoch: 0, train loss: 0.30464, val loss: 0.20570
Model Updated
Epoch: 100, train loss: 0.00678, val loss: 0.06032
Model Updated
Epoch: 200, train loss: 0.00331, val loss: 0.05221
Model Updated
Epoch: 300, train loss: 0.00241, val loss: 0.04836
Model Updated
Epoch: 400, train loss: 0.00186, val loss: 0.04785
Model Updated
Epoch: 500, train loss: 0.00155, val loss: 0.04688
Epoch: 600, train loss: 0.00146, val loss: 0.04710
Epoch: 700, train loss: 0.00148, val loss: 0.04896
Epoch: 800, train loss: 0.00115, val loss: 0.04834
Epoch: 900, train loss: 0.00137, val loss: 0.04947
Epoch: 1000, train loss: 0.00099, val loss: 0.04858
Epoch: 1100, train loss: 0.00125, val loss: 0.05136
Epoch: 1200, train loss: 0.00094, val loss: 0.04829
Epoch: 1300, train loss: 0.00090, val loss: 0.04766
Epoch: 1400, train loss: 0.00082, val loss: 0.04768
Epoch: 1500, train loss: 0.00080, val loss: 0.04779
Epoch: 1600, train loss: 0.00074, val loss: 0.04706
Epoch: 1700, train loss: 0.00073, val loss: 0.04716
Model Updated
Epoch: 1800, train loss: 0.00069, val loss: 0.04622
Epoch: 1900, train loss: 0.00074, val loss: 0.04669
Model Updated
Epoch: 2000, train loss: 0.00064, val loss: 0.04540
Model Updated
Epoch: 2100, train loss: 0.00062, val loss: 0.04452
Epoch: 2200, train loss: 0.00063, val loss: 0.04463
Model Updated
Epoch: 2300, train loss: 0.00059, val loss: 0.04450
Model Updated
Epoch: 2400, train loss: 0.00058, val loss: 0.04363
Epoch: 2500, train loss: 0.00058, val loss: 0.04426
Epoch: 2600, train loss: 0.00057, val loss: 0.04455
Epoch: 2700, train loss: 0.00057, val loss: 0.04443
Model Updated
Epoch: 2800, train loss: 0.00052, val loss: 0.04349
Model Updated
Epoch: 2900, train loss: 0.00049, val loss: 0.04322
(96, 51)
(954, 51)

In [ ]:
np.sort(np.load('/content/LR_StockPicking/10/top_idxs.npy'))

array([ 1, 13, 15, 21, 23, 29, 30, 39, 42, 44])

In [ ]:
np.sort(np.load('/content/SVR_StockPicking/10/top_idxs.npy'))

array([ 1,  3,  5, 10, 21, 23, 24, 34, 40, 50])

In [ ]:
# !zip -r /content/LR_StockPicking.zip /content/LR_StockPicking
# !zip -r /content/SVR_StockPicking.zip /content/SVR_StockPicking
!zip -r /content/LSTM_StockPicking_window_5.zip /content/LSTM_StockPicking_window_5

# TEMP

In [ ]:
!gdown --id 1dkIQbawpE7BKnxGh_OTKI1qVHWCuhCXh
!gdown --id 
!gdown --id

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1dkIQbawpE7BKnxGh_OTKI1qVHWCuhCXh
To: /content/mtp_data.csv
100% 851k/851k [00:00<00:00, 22.5MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1aR_9DxDYROg0gy3vlajzrcGCNoXher6E
To: /content/run_lr_train.sh
100% 682/682 [00:00<00:00, 1.15MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1J6JVeE8oypcvjq-vPnPCBX4DecQC1-9Y
To: /content/lr_asset_selection.py
100% 3.25k/3.25k [00:00<00:00, 5.46MB/s]

In [ ]:
!bash run_lr_train.sh

(954, 51)
(954, 51)
(954, 51)
(954, 51)
(954, 51)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.sort(np.load('/content/LR_Data2/1/top_idxs.npy'))

array([ 1,  3,  5, 10, 17, 19, 21, 23, 28, 31, 38, 40, 41, 48, 50])

In [ ]:
np.sort(np.load('/content/LR_Data2/5/top_idxs.npy'))

array([ 1,  3, 10, 11, 13, 21, 23, 24, 28, 29, 30, 39, 41, 42, 45])

In [ ]:
pd.read_csv('/content/mtp_data.csv', index_col=0)

,^NSEI,ONGC.NS,UPL.NS,ITC.NS,SUNPHARMA.NS,IOC.NS,JSWSTEEL.NS,SBIN.NS,SHREECEM.NS,HINDUNILVR.NS,...,KOTAKBANK.NS,BAJAJFINSV.NS,POWERGRID.NS,ASIANPAINT.NS,EICHERMOT.NS,TATAMOTORS.NS,DRREDDY.NS,HDFCBANK.NS,HDFC.NS,MARUTI.NS
0,10283.599609,142.570755,461.820221,219.472366,497.929108,137.465652,243.074020,334.412537,17980.212891,1207.996460,...,1021.619751,5122.470215,124.082924,1140.235840,2765.153076,421.799988,2228.211426,895.502197,1609.008423,7966.571289
1,10298.750000,144.497406,464.817383,220.493179,497.977264,136.700287,242.481430,329.953705,17216.855469,1204.546875,...,1038.942871,5166.208008,124.201874,1135.416992,2759.052246,423.000000,2182.017822,901.682983,1593.630493,8040.337402
2,10326.900391,145.219864,481.142456,217.600906,518.102356,137.813507,245.125443,327.625183,16725.525391,1207.240234,...,1028.259399,5198.812012,122.893265,1129.527710,2739.318359,424.250000,2296.853027,905.656372,1598.630859,8039.525879
3,10342.299805,145.541016,476.423492,219.599976,515.406250,137.761353,244.851959,332.232635,16819.513672,1200.719116,...,1024.664917,5169.003906,123.160934,1143.156372,2717.494873,428.600006,2264.714844,910.071228,1620.942749,8123.835449
4,10348.750000,145.862076,477.762665,219.599976,524.553955,137.326477,243.301971,331.885864,16929.433594,1197.930908,...,1020.521423,5126.314941,124.350624,1128.845825,2757.274170,426.250000,2212.525879,903.988525,1608.159302,8076.360840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,17822.949219,131.455353,726.849976,237.023010,763.822693,110.018982,677.250000,449.799988,29866.380859,2765.306152,...,2024.000000,18503.849609,170.912872,3316.733398,2857.050049,321.500000,4797.299805,1570.000000,2817.399902,6846.700195
950,17853.199219,129.880753,718.650024,233.064484,764.418030,109.319702,659.150024,440.750000,29359.828125,2729.873779,...,2028.099976,18526.000000,168.899323,3444.532715,2931.000000,317.950012,4790.350098,1601.550049,2839.000000,6952.250000
951,17855.099609,133.602539,725.849976,233.308838,757.075989,110.625015,648.650024,446.600006,29423.914062,2692.950684,...,2033.349976,18031.099609,168.755493,3426.603516,2879.350098,331.649994,4791.649902,1625.099976,2839.800049,7403.450195
952,17748.599609,135.701996,716.799988,232.380295,769.031616,114.634171,660.849976,444.899994,29191.275391,2707.213135,...,2068.199951,17550.349609,176.378265,3375.713623,2883.050049,329.299988,4833.149902,1615.050049,2804.949951,7423.850098
953,17711.300781,138.135483,717.150024,232.722397,804.948242,118.829811,679.799988,460.000000,29330.480469,2668.898682,...,2030.449951,17433.750000,187.021362,3319.130615,2843.250000,330.250000,4881.000000,1593.849976,2746.449951,7384.049805

In [ ]:
%pycat run_lr_train.sh

In [ ]:
%%writefile run_lr_train.sh
python lr_asset_selection.py --exp_name LR_StockPicking/2 --test_size 0.02 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/4 --test_size 0.04 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/6 --test_size 0.06 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/8 --test_size 0.08 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/10 --test_size 0.1 --num_stocks 10

Overwriting run_lr_train.sh

In [ ]:
%pycat lr_asset_selection.py

In [ ]:
%%writefile lr_asset_selection.py
import os
import json
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Function to prepare data
def prepare_data(X, window_size, sc = None):
    '''
    window_size : number of timesteps to look back for predicting the next timestep
    '''
    nAssets = X.shape[1]
    if sc is None:
        sc = MinMaxScaler()
        X = sc.fit_transform(X)
    else:
        X = sc.transform(X)
    
    x = []
    y = []
    dim=X.shape[1]
    for i in range(window_size, X.shape[0]):
        x.append(X[(i - window_size):i, :].reshape(window_size, dim))
        y.append(X[i, :].reshape(1, dim))
    
    x = np.array(x); y = np.squeeze(np.array(y));
    
    return x.reshape(-1, nAssets * window_size), y, sc

def make_grid_plot(y,preds):

    # Hard coded for 51 assets (i.e. plots); needs change in values if the number of input assets are changed
    fig, axs = plt.subplots(17, 3, figsize = (15,30))

    for i in range(17):
        for j in range(3):
            idx = i*3 + j
            axs[i,j].plot(preds[:, idx], color = 'orange', label = 'preds')
            axs[i,j].plot(sc.inverse_transform(y)[:, idx], color = 'blue', label = 'true')
            axs[i,j].legend(loc = 'upper left')
    return fig


# Parse Arguments
parser = argparse.ArgumentParser()
parser.add_argument("-ename", "--exp_name", type = str, default = "default_exp",
                    help = "Path to output folder for trained model")
parser.add_argument("-tsize", "--test_size", type = float, default = 0.1,
                    help = "Test Size")
parser.add_argument("-ws", "--window_size", type = int, default = 5,
                    help = "Window Size")
parser.add_argument("-nstocks", "--num_stocks", type = int, default = 4,
                    help = "Number of stocks to be picked for portfolio")
args = parser.parse_args()


EXP_NAME = args.exp_name
# Make experiment directory #
if not os.path.exists(args.exp_name):
        os.makedirs(args.exp_name)

# Reading data
data = pd.read_csv('mtp_data.csv', index_col = 0)
data = np.array(data.iloc[:, :])

# Split into training, validation and testing parts
X_train, X_test = train_test_split(data, test_size = args.test_size, shuffle = False)
_xtrain = np.copy(X_train)
X_test = np.vstack([X_train[X_train.shape[0] - args.window_size:X_train.shape[0], :], X_test])

xtr, ytr, sc = prepare_data(X_train, args.window_size)
xte, yte, _ = prepare_data(X_test, args.window_size, sc)
reg = LinearRegression().fit(xtr, ytr)
preds = sc.inverse_transform(reg.predict(xte))

# Pick top 'num_stocks' best stocks #
num_stocks = X_train.shape[1]
X = preds
R = np.copy(X)
for i in range(1, R.shape[0]):
    R[i] = (X[i] - X[i-1])/X[i-1]
    
R = R[1:, :]

expected_returns = {}
for i in range(num_stocks):
    expected_returns[i] = np.mean(R[:, i])

top_idxs = list(dict(sorted(expected_returns.items(), key = lambda item: item[1], reverse = True)).keys())[:args.num_stocks]
np.save(os.path.join(EXP_NAME, 'top_idxs.npy'), np.array(top_idxs))

with open(os.path.join(EXP_NAME, 'commandline_args.txt'), 'w') as f:
    json.dump(args.__dict__, f, indent = 2)


# Save predictions on test set along with other data #
arr = np.vstack([_xtrain, preds])
print(arr.shape)
np.save(os.path.join(EXP_NAME, 'preds_array.npy'), arr)

preds_tr = sc.inverse_transform(reg.predict(xtr))
train_fig = make_grid_plot(ytr,preds_tr)
test_fig = make_grid_plot(yte,preds)
train_fig.savefig(os.path.join(EXP_NAME, 'train_plot.png'))
test_fig.savefig(os.path.join(EXP_NAME, 'test_plot.png'))

Overwriting lr_asset_selection.py

In [ ]:
%pycat run_lr_train.sh